// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dorghxtadxvberjosnpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvcmdoeHRhZHh2YmVyam9zbnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzY5OTIsImV4cCI6MjA1OTIxMjk5Mn0._A1mruxAV8K7Ak7fCV-ZscbMHqXhqTZbq1PTFVNyl4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);